
decline_all_test.exs:9:"test all fail" assert_value "foo" == "bar<NOEOL>\n" failed

-bar
+foo

Accept new value? [y,n,?] 

  1) test all fail (DeclineAllTest)
     decline_all_test.exs:8
     AssertValue assertion failed
     code:  "foo" == "bar<NOEOL>\n"
     left: "foo"
     right: "bar"
     stacktrace:
       decline_all_test.exs:9: (test)

.

  2) test all fail again (DeclineAllTest)
     decline_all_test.exs:26
     AssertValue assertion failed
     code:  "foo" == "bar<NOEOL>\n"
     left: "foo"
     right: "bar"
     stacktrace:
       decline_all_test.exs:27: (test)


3 tests, 2 failures
